// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dziennik_elektroniczny.Infrastructure;

#nullable disable

namespace dziennik_elektroniczny.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240906123716_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.ContactStudentInfo1A", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("ContactStudentInfo1A");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsOfTeaching")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.TeacherAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherRef")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherRef")
                        .IsUnique();

                    b.ToTable("TeacherAddress");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.TeacherContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherRef")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherRef")
                        .IsUnique();

                    b.ToTable("TeacherContactInfo");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1A._1AEnglish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HomeworkAvarage")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuizAvarage")
                        .HasColumnType("float");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.Property<double>("TestAvarage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("_1AEnglish");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1ABiology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HomeworkAvarage")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuizAvarage")
                        .HasColumnType("float");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.Property<double>("TestAvarage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("_1ABiology");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AChemistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HomeworkAvarage")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuizAvarage")
                        .HasColumnType("float");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.Property<double>("TestAvarage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("_1AChemistry");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AGeography", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HomeworkAvarage")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuizAvarage")
                        .HasColumnType("float");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.Property<double>("TestAvarage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("_1AGeography");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AGerman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HomeworkAvarage")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuizAvarage")
                        .HasColumnType("float");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.Property<double>("TestAvarage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("_1AGerman");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HomeworkAvarage")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuizAvarage")
                        .HasColumnType("float");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.Property<double>("TestAvarage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("_1AHistory");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AMath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HomeworkAvarage")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuizAvarage")
                        .HasColumnType("float");

                    b.Property<int>("StudentRef")
                        .HasColumnType("int");

                    b.Property<double>("TestAvarage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("_1AMath");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_1AStudents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.ContactStudentInfo1A", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("ContactStudentInfo1A")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model.ContactStudentInfo1A", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.TeacherAddress", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.Teacher", "Teacher")
                        .WithOne("TeacherAddress")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.TeacherAddress", "TeacherRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.TeacherContactInfo", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.Teacher", "Teacher")
                        .WithOne("TeacherContactInfo")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.TeacherContactInfo", "TeacherRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1A._1AEnglish", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("_1AEnglish")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model._1A._1AEnglish", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1ABiology", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("_1ABiology")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model._1ABiology", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AChemistry", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("_1AChemistry")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model._1AChemistry", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AGeography", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("_1AGeography")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model._1AGeography", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AGerman", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("_1AGerman")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model._1AGerman", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AHistory", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("_1AHistory")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model._1AHistory", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AMath", b =>
                {
                    b.HasOne("dziennik_elektroniczny.Infrastructure.Model._1AStudent", "_1AStudent")
                        .WithOne("_1AMath")
                        .HasForeignKey("dziennik_elektroniczny.Infrastructure.Model._1AMath", "StudentRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_1AStudent");
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model.TeacherInfo.Teacher", b =>
                {
                    b.Navigation("TeacherAddress")
                        .IsRequired();

                    b.Navigation("TeacherContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("dziennik_elektroniczny.Infrastructure.Model._1AStudent", b =>
                {
                    b.Navigation("ContactStudentInfo1A")
                        .IsRequired();

                    b.Navigation("_1ABiology")
                        .IsRequired();

                    b.Navigation("_1AChemistry")
                        .IsRequired();

                    b.Navigation("_1AEnglish")
                        .IsRequired();

                    b.Navigation("_1AGeography")
                        .IsRequired();

                    b.Navigation("_1AGerman")
                        .IsRequired();

                    b.Navigation("_1AHistory")
                        .IsRequired();

                    b.Navigation("_1AMath")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
